;;; publish.el --- Export readme.org to HTML with Sakura CSS  -*- lexical-binding: t; -*-

(require 'ox-html)

(setq org-html-head
      (concat
       "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sakura.css/css/sakura.css\" media=\"screen\" />\n"
       "<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sakura.css/css/sakura-dark.css\" media=\"screen and (prefers-color-scheme: dark)\" />\n"
       "<style>\n"
       "/* Override Sakura layout */\n"
       "body { max-width: none; margin: 0; padding: 0; }\n"
       "\n"
       "/* Grid layout */\n"
       "#content {\n"
       "  display: grid;\n"
       "  grid-template-columns: 250px 1fr;\n"
       "  max-width: 80em;\n"
       "  margin: 0 auto;\n"
       "  padding: 1rem 2rem;\n"
       "  gap: 0 2rem;\n"
       "}\n"
       "\n"
       "/* Title + all sections in column 2 */\n"
       "h1.title, #content > .outline-2, #content > .outline-3 { grid-column: 2; }\n"
       "\n"
       "/* Sidebar TOC */\n"
       "#table-of-contents {\n"
       "  grid-column: 1;\n"
       "  grid-row: 1 / -1;\n"
       "  position: sticky;\n"
       "  top: 1rem;\n"
       "  align-self: start;\n"
       "  max-height: calc(100vh - 2rem);\n"
       "  overflow-y: auto;\n"
       "  padding: 1rem 1rem 1rem 0;\n"
       "  border-right: 1px solid rgba(0,0,0,0.1);\n"
       "  font-size: 0.85em;\n"
       "}\n"
       "@media (prefers-color-scheme: dark) {\n"
       "  #table-of-contents { border-right-color: rgba(255,255,255,0.1); }\n"
       "}\n"
       "#table-of-contents h2 { font-size: 1.1em; margin-top: 0; }\n"
       "#table-of-contents ul { list-style: none; padding-left: 0.8em; margin: 0.3em 0; }\n"
       "#table-of-contents > div > ul { padding-left: 0; }\n"
       "#table-of-contents a { text-decoration: none; display: block; padding: 0.15em 0.4em; border-radius: 3px; }\n"
       "#table-of-contents a:hover { background: rgba(0,0,0,0.05); }\n"
       "@media (prefers-color-scheme: dark) {\n"
       "  #table-of-contents a:hover { background: rgba(255,255,255,0.08); }\n"
       "}\n"
       "#table-of-contents a.active {\n"
       "  background: rgba(0,0,0,0.08);\n"
       "  font-weight: 600;\n"
       "}\n"
       "@media (prefers-color-scheme: dark) {\n"
       "  #table-of-contents a.active { background: rgba(255,255,255,0.12); }\n"
       "}\n"
       "\n"
       "/* Hamburger button (hidden on desktop) */\n"
       "#sidebar-toggle {\n"
       "  display: none;\n"
       "  position: fixed;\n"
       "  top: 0.8rem;\n"
       "  left: 0.8rem;\n"
       "  z-index: 1000;\n"
       "  background: var(--color-bg, #fff);\n"
       "  border: 1px solid rgba(0,0,0,0.2);\n"
       "  border-radius: 4px;\n"
       "  padding: 0.4rem 0.55rem;\n"
       "  font-size: 1.3rem;\n"
       "  line-height: 1;\n"
       "  cursor: pointer;\n"
       "}\n"
       "@media (prefers-color-scheme: dark) {\n"
       "  #sidebar-toggle { border-color: rgba(255,255,255,0.2); }\n"
       "}\n"
       "\n"
       "/* Mobile */\n"
       "@media (max-width: 768px) {\n"
       "  #content {\n"
       "    display: block;\n"
       "    padding: 1rem;\n"
       "  }\n"
       "  #sidebar-toggle { display: block; }\n"
       "  #table-of-contents {\n"
       "    position: fixed;\n"
       "    top: 0; left: 0;\n"
       "    width: 280px;\n"
       "    height: 100vh;\n"
       "    max-height: 100vh;\n"
       "    background: var(--color-bg, #fff);\n"
       "    border-right: 1px solid rgba(0,0,0,0.15);\n"
       "    padding: 3rem 1rem 1rem;\n"
       "    transform: translateX(-100%);\n"
       "    transition: transform 0.25s ease;\n"
       "    z-index: 999;\n"
       "    box-shadow: none;\n"
       "  }\n"
       "  body.sidebar-open #table-of-contents {\n"
       "    transform: translateX(0);\n"
       "    box-shadow: 2px 0 8px rgba(0,0,0,0.15);\n"
       "  }\n"
       "}\n"
       "\n"
       "pre { overflow-x: auto; }\n"
       "</style>\n"
       "<script>\n"
       "document.addEventListener('DOMContentLoaded', function() {\n"
       "  /* Sidebar toggle */\n"
       "  var toggle = document.getElementById('sidebar-toggle');\n"
       "  if (toggle) {\n"
       "    toggle.addEventListener('click', function() {\n"
       "      document.body.classList.toggle('sidebar-open');\n"
       "    });\n"
       "    /* Close sidebar when clicking a TOC link on mobile */\n"
       "    var toc = document.getElementById('table-of-contents');\n"
       "    if (toc) {\n"
       "      toc.addEventListener('click', function(e) {\n"
       "        if (e.target.tagName === 'A' && window.innerWidth <= 768) {\n"
       "          document.body.classList.remove('sidebar-open');\n"
       "        }\n"
       "      });\n"
       "    }\n"
       "  }\n"
       "\n"
       "  /* Active TOC highlight via IntersectionObserver */\n"
       "  var headings = document.querySelectorAll('#content h2, #content h3');\n"
       "  var tocLinks = document.querySelectorAll('#table-of-contents a');\n"
       "  if (headings.length && tocLinks.length && 'IntersectionObserver' in window) {\n"
       "    var linkMap = {};\n"
       "    tocLinks.forEach(function(link) {\n"
       "      var href = link.getAttribute('href');\n"
       "      if (href && href.startsWith('#')) linkMap[href.slice(1)] = link;\n"
       "    });\n"
       "    var currentActive = null;\n"
       "    var observer = new IntersectionObserver(function(entries) {\n"
       "      entries.forEach(function(entry) {\n"
       "        if (entry.isIntersecting) {\n"
       "          var id = entry.target.id || (entry.target.parentElement && entry.target.parentElement.id);\n"
       "          if (id && linkMap[id]) {\n"
       "            if (currentActive) currentActive.classList.remove('active');\n"
       "            linkMap[id].classList.add('active');\n"
       "            currentActive = linkMap[id];\n"
       "          }\n"
       "        }\n"
       "      });\n"
       "    }, { rootMargin: '0px 0px -70% 0px', threshold: 0 });\n"
       "    headings.forEach(function(h) { observer.observe(h); });\n"
       "  }\n"
       "});\n"
       "</script>\n"))

(setq org-html-head-include-default-style nil)
(setq org-html-head-include-scripts nil)
(setq org-html-validation-link nil)
(setq org-html-postamble nil)
(setq org-html-htmlize-output-type nil)
(setq org-html-preamble "<button id=\"sidebar-toggle\" aria-label=\"Toggle navigation\">&#9776;</button>")

(with-current-buffer (find-file-noselect "readme.org")
  (org-html-export-to-html))
