;;; publish.el --- Export readme.org to HTML with oat.ink  -*- lexical-binding: t; -*-

(require 'ox-html)

(setq org-html-head
      (concat
       "<link rel=\"stylesheet\" href=\"https://unpkg.com/@knadh/oat/oat.min.css\">\n"
       "<script defer data-domain=\"vpnproxyjump\" src=\"https://analytics.turtletech.us/js/script.outbound-links.js\"></script>\n"
       "<style>\n"
       "/* Hide until JS restructures DOM into oat sidebar layout */\n"
       "body:not([data-sidebar-layout]) { opacity: 0; }\n"
       "pre { overflow-x: auto; }\n"
       "main > div { max-width: 55em; margin: 0 auto; padding: var(--space-3); }\n"
       "#theme-toggle { background: none; border: none; cursor: pointer; font-size: 1.2rem; padding: 0.3rem; margin-left: auto; color: inherit; }\n"
       "</style>\n"
       "<script>\n"
       "document.addEventListener('DOMContentLoaded', function() {\n"
       "  var body = document.body;\n"
       "  var content = document.getElementById('content');\n"
       "  var toc = document.getElementById('table-of-contents');\n"
       "  var preamble = document.getElementById('preamble');\n"
       "  if (!content) return;\n"
       "\n"
       "  /* Top nav with toggle */\n"
       "  var topnav = document.createElement('nav');\n"
       "  topnav.setAttribute('data-topnav', '');\n"
       "  var btn = document.createElement('button');\n"
       "  btn.setAttribute('data-sidebar-toggle', '');\n"
       "  btn.setAttribute('aria-label', 'Toggle menu');\n"
       "  btn.className = 'outline';\n"
       "  btn.textContent = '\\u2630';\n"
       "  topnav.appendChild(btn);\n"
       "  var titleEl = content.querySelector('h1.title');\n"
       "  if (titleEl) {\n"
       "    var span = document.createElement('span');\n"
       "    span.textContent = titleEl.textContent;\n"
       "    topnav.appendChild(span);\n"
       "  }\n"
       "  var themeBtn = document.createElement('button');\n"
       "  themeBtn.id = 'theme-toggle';\n"
       "  themeBtn.setAttribute('aria-label', 'Toggle theme');\n"
       "  function updateIcon() {\n"
       "    themeBtn.textContent = document.documentElement.getAttribute('data-theme') === 'dark' ? '\\u2600' : '\\u263E';\n"
       "  }\n"
       "  themeBtn.addEventListener('click', function() {\n"
       "    var next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';\n"
       "    document.documentElement.setAttribute('data-theme', next);\n"
       "    localStorage.setItem('theme', next);\n"
       "    updateIcon();\n"
       "  });\n"
       "  topnav.appendChild(themeBtn);\n"
       "\n"
       "  /* Aside sidebar from TOC */\n"
       "  var aside = document.createElement('aside');\n"
       "  aside.setAttribute('data-sidebar', '');\n"
       "  if (toc) {\n"
       "    var tocHeader = document.createElement('header');\n"
       "    tocHeader.textContent = 'Contents';\n"
       "    aside.appendChild(tocHeader);\n"
       "    var tocNav = document.createElement('nav');\n"
       "    var tocList = toc.querySelector('#text-table-of-contents > ul');\n"
       "    if (tocList) tocNav.appendChild(tocList);\n"
       "    aside.appendChild(tocNav);\n"
       "    toc.remove();\n"
       "  }\n"
       "\n"
       "  /* Main content wrapper */\n"
       "  var main = document.createElement('main');\n"
       "  var wrapper = document.createElement('div');\n"
       "  while (content.firstChild) wrapper.appendChild(content.firstChild);\n"
       "  main.appendChild(wrapper);\n"
       "\n"
       "  /* Replace old structure */\n"
       "  if (preamble) preamble.remove();\n"
       "  content.remove();\n"
       "  body.insertBefore(main, body.firstChild);\n"
       "  body.insertBefore(aside, main);\n"
       "  body.insertBefore(topnav, aside);\n"
       "  body.setAttribute('data-sidebar-layout', '');\n"
       "\n"
       "  /* Load oat.ink JS after DOM is restructured */\n"
       "  var s = document.createElement('script');\n"
       "  s.src = 'https://unpkg.com/@knadh/oat/oat.min.js';\n"
       "  s.onload = updateIcon;\n"
       "  document.head.appendChild(s);\n"
       "\n"
       "  /* Active TOC highlight */\n"
       "  var headings = main.querySelectorAll('h2[id], h3[id]');\n"
       "  var tocLinks = aside.querySelectorAll('a');\n"
       "  if (headings.length && tocLinks.length && 'IntersectionObserver' in window) {\n"
       "    var linkMap = {};\n"
       "    tocLinks.forEach(function(link) {\n"
       "      var href = link.getAttribute('href');\n"
       "      if (href && href.startsWith('#')) linkMap[href.slice(1)] = link;\n"
       "    });\n"
       "    var current = null;\n"
       "    var observer = new IntersectionObserver(function(entries) {\n"
       "      entries.forEach(function(entry) {\n"
       "        if (entry.isIntersecting && linkMap[entry.target.id]) {\n"
       "          if (current) current.removeAttribute('aria-current');\n"
       "          linkMap[entry.target.id].setAttribute('aria-current', 'page');\n"
       "          current = linkMap[entry.target.id];\n"
       "        }\n"
       "      });\n"
       "    }, { rootMargin: '0px 0px -70% 0px', threshold: 0 });\n"
       "    headings.forEach(function(h) { observer.observe(h); });\n"
       "  }\n"
       "});\n"
       "</script>\n"))

(setq org-html-head-include-default-style nil)
(setq org-html-head-include-scripts nil)
(setq org-html-validation-link nil)
(setq org-html-postamble nil)
(setq org-html-preamble nil)
(setq org-html-htmlize-output-type nil)

(with-current-buffer (find-file-noselect "readme.org")
  (org-html-export-to-html))
